# Reproduce HANAMI Fig. 5 from the source table generated by
# analyze_clinical_concordance.py. No result values are hard-coded here.
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
})

parse_args <- function(args) {
  values <- list(
    source = NULL,
    output_pdf = NULL,
    output_png = NULL,
    width = 13.5,
    height = 6.6,
    dpi = 300
  )
  i <- 1
  while (i <= length(args)) {
    key <- args[[i]]
    if (i == length(args)) stop("Missing value for argument: ", key)
    value <- args[[i + 1]]
    if (key == "--source") values$source <- value
    else if (key == "--output-pdf") values$output_pdf <- value
    else if (key == "--output-png") values$output_png <- value
    else if (key == "--width") values$width <- as.numeric(value)
    else if (key == "--height") values$height <- as.numeric(value)
    else if (key == "--dpi") values$dpi <- as.numeric(value)
    else stop("Unknown argument: ", key)
    i <- i + 2
  }
  required <- c("source", "output_pdf", "output_png")
  missing <- required[vapply(values[required], is.null, logical(1))]
  if (length(missing)) stop("Missing required arguments: ", paste(missing, collapse = ", "))
  values
}

args <- parse_args(commandArgs(trailingOnly = TRUE))
if (!file.exists(args$source)) {
  stop("Figure source table not found: ", args$source,
       ". Run analyze_clinical_concordance.py first.")
}

source <- read.csv(args$source, stringsAsFactors = FALSE, check.names = FALSE)
required_columns <- c(
  "panel", "panel_type", "panel_title", "method", "rank_percentile",
  "bar_order", "comparison_method", "reference_method", "significance"
)
missing_columns <- setdiff(required_columns, names(source))
if (length(missing_columns)) {
  stop("Figure source table lacks columns: ", paste(missing_columns, collapse = ", "))
}

palette <- c(
  "HANAMI" = "#2C8C99",
  "TriMoGCL" = "#E28B62",
  "TriNet" = "#92B1B6",
  "N2V-MLP" = "#CAD0BD",
  "RF" = "#E1A6AD"
)

format_title <- function(title, panel_type) {
  if (panel_type == "aggregate") {
    return(sub(
      "clinically documented",
      paste("clinically", "documented", sep = "\n"),
      title,
      fixed = TRUE
    ))
  }
  # Break after the drug-gene pair while preserving the manuscript labels.
  sub("^([^-]+-[^-]+)-", paste0("\\1-", "\n"), title)
}

bar_theme <- theme_classic(base_size = 11) +
  theme(
    plot.title = element_text(face = "bold", size = 9, hjust = 0.5, lineheight = 0.95),
    axis.title.y = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 7.5),
    legend.position = "none",
    plot.margin = margin(6, 8, 6, 6)
  )

draw_panel <- function(panel_data) {
  panel_data <- panel_data[order(panel_data$bar_order), , drop = FALSE]
  panel_data$method <- factor(panel_data$method, levels = panel_data$method)
  title <- format_title(panel_data$panel_title[[1]], panel_data$panel_type[[1]])
  significance <- panel_data$significance[[1]]
  has_significance <- !is.na(significance) && nzchar(significance) && significance != "ns"
  maximum <- max(panel_data$rank_percentile)
  ymax <- maximum * 1.18

  graph <- ggplot(panel_data, aes(method, rank_percentile, fill = method)) +
    geom_col(width = 0.68) +
    geom_text(
      aes(label = sprintf("%.2f", rank_percentile)),
      vjust = -0.35,
      size = 2.7
    ) +
    scale_fill_manual(values = palette) +
    scale_y_continuous(limits = c(0, ymax), expand = expansion(mult = c(0, 0.02))) +
    labs(title = title, x = NULL, y = "Rank percentile (%)") +
    bar_theme

  if (has_significance) {
    methods <- as.character(panel_data$method)
    x1 <- match(panel_data$comparison_method[[1]], methods)
    x2 <- match(panel_data$reference_method[[1]], methods)
    if (is.na(x1) || is.na(x2)) stop("Significance comparison methods are absent from panel")
    compared <- panel_data$rank_percentile[methods %in% c(
      panel_data$comparison_method[[1]], panel_data$reference_method[[1]]
    )]
    y <- max(compared) * 1.22
    tick <- ymax * 0.02
    graph <- graph +
      annotate("segment", x = x1, xend = x2, y = y, yend = y, linewidth = 0.4) +
      annotate("segment", x = x1, xend = x1, y = y, yend = y - tick, linewidth = 0.4) +
      annotate("segment", x = x2, xend = x2, y = y, yend = y - tick, linewidth = 0.4) +
      annotate(
        "text", x = (x1 + x2) / 2, y = y + ymax * 0.005,
        label = significance, size = 4.6, vjust = 0
      )
  }
  graph
}

panel_order <- unique(source$panel)
plots <- lapply(panel_order, function(panel_id) {
  draw_panel(source[source$panel == panel_id, , drop = FALSE])
})
panel <- wrap_plots(plots, ncol = 4) +
  plot_annotation(
    tag_levels = "a",
    theme = theme(plot.tag = element_text(face = "bold", size = 12))
  )

dir.create(dirname(args$output_pdf), recursive = TRUE, showWarnings = FALSE)
dir.create(dirname(args$output_png), recursive = TRUE, showWarnings = FALSE)
ggsave(args$output_pdf, panel, width = args$width, height = args$height)
ggsave(
  args$output_png, panel, width = args$width, height = args$height,
  dpi = args$dpi, bg = "white"
)
cat("Wrote", args$output_pdf, "and", args$output_png, "\n")
